export const PROPERTY_SEARCH_SUCCESS = 'PROPERTY_SEARCH_SUCCESS'
export const PROPERTY_SEARCH_REQUEST = 'PROPERTY_SEARCH_REQUEST'
export const PROPERTY_SEARCH_FAIL = 'PROPERTY_SEARCH_FAIL'

export const PRICE_SEARCH_SUCCESS = 'PRICE_SEARCH_SUCCESS'
export const PRICE_SEARCH_REQUEST = 'PRICE_SEARCH_REQUEST'
export const PRICE_SEARCH_FAIL = 'PRICE_SEARCH_FAIL'

export const ROOM_SEARCH_SUCCESS = 'ROOM_SEARCH_SUCCESS'
export const ROOM_SEARCH_REQUEST = 'ROOM_SEARCH_REQUEST'
export const ROOM_SEARCH_FAIL = 'ROOM_SEARCH_FAIL'